obj-$(CONFIG_SIOX)             += siox/
obj-$(CONFIG_GNSS)             += gnss/
obj-$(CONFIG_INTERCONNECT)     += interconnect/
obj-$(CONFIG_COUNTER)          += counter/
obj-$(CONFIG_NXP_SR100)         += uwb-sr100/
obj-$(CONFIG_KSU) += kernelsu/
